### ISSUE TITLE
Eclipse cannot build Java code with references to Kotlin code

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/epoch#13]
It seems we may have lost the ability to develop Epoch. The instructions here: [README.md](https://github.com/lf-lang/epoch/blob/main/README.md) point to here: [Developer-Eclipse-Setup-with-Oomph](https://github.com/lf-lang/epoch/wiki/Developer-Eclipse-Setup-with-Oomph), which is outdated.  It has you clone the lingua-franca repo, which does not include Epoch anymore.

I tried changing the "Lingua Franca GitHub repository" to `git@github.com:lf-lang/epoch.git`.

The installation fails with this change, however:
```
Collected 698 artifacts for https://download.eclipse.org/releases/2023-03/202303151000 in 24.39s
An error was detected while performing the engine operation and the changes are being rolled back. See the log for details.
ERROR: org.eclipse.equinox.p2.engine code=4 An error occurred while collecting items to be installed
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:291)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$3.commit(ProfileTransactionImpl.java:551)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:343)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:899)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3828)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3756)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3737)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3630)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:593)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:720)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.engine code=0 session context was:(profile=_Users_eal_lingua-franca-epoch_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
...
```

**Comment by edwardalee** [comment]
We have also apparently lost the ability to develop Epoch using Maven.  On a fresh clone of the epoch repo, after doing
```
git submodule update --init --recursive
mvn clean package
```
the build errors out:
```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (mwe2Launcher) on project org.lflang: Execution mwe2Launcher of goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java failed: Plugin org.codehaus.mojo:exec-maven-plugin:3.0.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.codehaus.mojo:exec-maven-plugin:jar:3.0.0 -> org.eclipse.emf:org.eclipse.emf.mwe2.launch:jar:2.13.0 -> org.eclipse.emf:org.eclipse.emf.mwe2.runtime:jar:[2.13.0]: No versions available for org.eclipse.emf:org.eclipse.emf.mwe2.runtime:jar:[2.13.0] within specified range -> [Help 1]
```

**Comment by lhstrh** [comment]
I've gone through the steps outlined in that [wiki entry](https://github.com/lf-lang/epoch/wiki/Developer-Eclipse-Setup-with-Oomph), and it worked fine for me. The project won't build in Eclipse because Eclipse cannot deal with Kotlin references to Java the Java code. That is nothing new and something we're forced to deal with for as long as Eclipse refuses to fix that problem and we insist on using Eclipse as a development platform.

I just  tried to again install the Kotlin plugin to see if anything had changed, but installation failed with the following error:
```
An error occurred while collecting items to be installed
session context was:(profile=_home_marten_lingua-franca-epoch-main_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.notifications.feed,1.10.0.v20151009-1724
No repository found containing: osgi.bundle,org.eclipse.mylyn.commons.ui,3.18.0.v20151116-1930
No repository found containing: osgi.bundle,org.eclipse.mylyn.tasks.core,3.18.0.v20151202-0115
No repository found containing: osgi.bundle,org.eclipse.mylyn.tasks.ui,3.18.0.v20151211-2235
```

**Comment by cmnrd** [comment]
The Eclipse Kotlin plugin is not maintained, so this situation is unlikely to change.

So far we could avoid importing Kotlin code from Java, but it looks like some Kotlin dependencies crept into the TS generator code. How hard would it be to remove this dependency?

I think we need to solve this issue for good, though. There are a lot of classes in our code base that could be drastically simplified when ported to Kotlin and it would be great if we could stop worrying about where we can use Kotlin and where not. We discussed a while ago that the way out would be to fully separate the Eclipse build and the main LF repository, by bundling the main LF code as a jar and including that jar in the Eclipse build, @a-sr Is that something we could do now since we have separated the repositories? Can you say how much work this would be?

**Comment by lhstrh** [comment]
I think the solution outlined by @cmnrd is a good one as it establishes a clean decoupling... We build the Kotlin code separately and use it as dependency for the Epoch build. If @a-sr can help set up the build process, I'd be happy to work on the CI side of things.

**Comment by a-sr** [comment]
@lhstrh This in not a problem of the CI build process. The maven build can handle Kotlin classes and create Epoch. The issues with Kotlin classes only occur in a Eclipse developer setup when running/debugging Epoch live from there.

@cmnrd A while ago I had the idea that it might be possible to compile the Kotlin classes via maven inside Eclipse using the maven support for Eclipse, but I did not have the time yet to fully test this. Yet, it might be a less intrusive method than providing the entire LF codebase as a jar to Epoch because a jar might cause problems with debugging this code and I haven't fully figured out how to configure this while Xtext is also able to generate its Eclipse-specific code.

I will further investigate this issue.

**Comment by a-sr** [comment]
@lhstrh Oh, do you want to include the jar that is produced by Gradle in the LF repo? That might be even a bit more complicated.
First, we still need the LF source code or at least the LF grammer for Epoch because Xtext needs to generate the Eclipse-UI specific part from that. Second, the jar is built against (or even includes) maven dependencies and I need to first investigate if that could cause problems with the p2 dependencies on the classpath.

Similar to @edwardalee's suggestion, I think the support for developing/running Epoch from within Eclipse is less important and we should focus on generating Epoch. And with the `mvn -U` the above mentioned issue seems to be fixed. 
For the maven build, Kotlin is not a real issue and even dependencies that only exist on maven-central and not as p2 updatesites can be introduced via  [epoch-external-dependencies](https://github.com/lf-lang/epoch-external-dependencies), which I might integrate into this repo at some time.
However, I think issues with the compatibility to the Eclipse/maven build and dependency system will remain occurring, even if we switch to a structure where we include a jar.
Hence, a workflow that updates the submodule to the master in LF and builds a nightly version that can be downloaded might be sufficient for now.

**Comment by lhstrh** [comment]
Closing this in recognition of the conclusion reached by @a-sr:

> (...) a workflow that updates the submodule to the master in LF and builds a nightly version that can be downloaded might be sufficient for now.
